name: build-test
'on':
  push:
    branches:
      - feat/gh-workflow
  pull_request:
    braches:
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Install virtme-ng
        run: >
          sudo apt update && sudo apt install -y virtme-ng
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Prerequisites and build script
        run: |
          cat <<'EOF' > build.sh
          #!/bin/bash
          set -e

          KERNEL_VER_ARG=$1
          URL_PREFIX="https://kernel.ubuntu.com/~kernel-ppa/mainline/${KERNEL_VER_ARG}/amd64"

          echo "Download Prerequisites"
          sudo apt update && \
          sudo apt install -y git build-essential lua5.4 dwarves clang llvm \
            libelf-dev linux-tools-common \
            pkg-config libpcap-dev m4

          echo "Downloading the kernel headers"
          curl -s "${URL_PREFIX}/CHECKSUMS" \
            | grep -E "linux-headers.*amd64.deb" \
            | cut -d ' ' -f 3 \
            | sort | uniq > files.txt

          cat files.txt

          # Download the headers
          # Read each line of files.txt
          while IFS= read -r line; do
                FULL_URL="${URL_PREFIX}/${line}"

                echo "Downloading $FULL_URL"
                wget -q "$FULL_URL" -O "$line" || { echo "Failed to download $line"; continue; }

                echo "Installing $line"
                sudo dpkg -i "$line"
          done < files.txt
          
          echo "Fixing missing dependencies"
          sudo apt-get install -f -y

          echo "Starting build"
          make
          EOF

          chmod +x build.sh

      - name: Run build in v6.8 with virtme-ng
        run: |
          vng -r v6.8 --exec ./build.sh --network user

